config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'game', to: 'pages#game'
  get 'hiscores', to: 'pages#hiscores'
  post '/played', to: 'pages#played'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def username
    email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home, :hiscores]
  before_action :set_stats, only: [:game]


  def home
  end

  def game
  end

  def hiscores
    @users = User.order('wins DESC')
  end

  def played
    current_user.wins += 1 if params[:win]
    current_user.losses += 1 if params[:loss]
    current_user.ties += 1 if params[:tie]
    current_user.save
  end

  private

  def set_stats
    @wins = current_user.wins
    @losses = current_user.losses
    @ties = current_user.ties
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Tic Tac', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Play Game', game_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Hi-Scores', hiscores_path, class: 'nav-link' %>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
    <% if current_user %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'Play a Game', game_path, class: 'dropdown-item' %>
          <%= link_to 'Account Settings', edit_user_registration_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>

        </div>
      </li>
    <% else %>
      <%= link_to 'Create an Account', new_user_registration_path, class: 'nav-item pr-3' %>
      <%= link_to 'Login', new_user_session_path, class: 'nav-item' %>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tictac</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/nav' %>
    <div class="container">
    <%= yield %>

  </div>
  </body>
</html>

app/views/pages/game.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.min.js"></script>
<div class="container" style="text-align: center">
    <h1 id="scoreText" style="text-align: center">
        <%= pluralize(@wins, "Win") %> / <%= pluralize(@losses, "Loss") %> / <%= pluralize(@ties, "Tie") %>
    </h1>
    <div style="font-size: 32px" id="result"></div>
</div>

<script>
    var canvas;
    var board;
    var human = 'O';
    var computer = 'X';
    var currentPlayer;
    var available = [];
    var nodeWidth;
    var nodeHeight;
    var resultText = document.getElementById("result");
    var scoreText = document.getElementById("scoreText");
    var canvasOffset = resultText.getBoundingClientRect().bottom;
    var winner;
    var gameInProgress;
    var score = [
        parseInt("<%= @wins %>"),
        parseInt("<%= @losses %>"),
        parseInt("<%= @ties %>")
    ];

    function newGame() {
        noLoop();
        resultText.innerHTML = "";
        board = [
            ['', '', ''],
            ['', '', ''],
            ['', '', '']
        ]
        board[1][0] = human;
        available = board;
        currentPlayer = random([human, computer]);
        gameInProgress = true;
        loop();

    }


    function setup() {
        canvas = createCanvas(windowWidth, windowHeight - canvasOffset * 2);
        nodeWidth = width / 3;
        nodeHeight = height / 3;
        centerCanvas();
        newGame();
    }

    function centerCanvas() {
        var canvasX = (windowWidth - width) / 2;
        var canvasY = (windowHeight - height) / 2 + canvasOffset;
        canvas.position(canvasX, canvasY);
    }

    function windowResized() {
        resizeCanvas(windowWidth, windowHeight - canvasOffset * 2);
        nodeWidth = width / 3;
        nodeHeight = height / 3;
        centerCanvas();
        drawGrid();
    }

    function drawGrid() {
        line(nodeWidth, 0, nodeWidth, height);
        line(nodeWidth * 2, 0, nodeWidth * 2, height);
        line(0, nodeHeight, width, nodeHeight);
        line(0, nodeHeight * 2, width, nodeHeight * 2);
    }

    function draw() {
        background(220);
        drawGrid();
        strokeWeight(4);

        for (let i = 0; i < 3; i++) {
            for (let j = 0; j < 3; j++) {
                // if i = 0, x = 0 +
                let x = nodeWidth * i + nodeWidth / 2;
                let y = nodeHeight * j + nodeHeight / 2;
                let spot = board[i][j]
                let xRadius = nodeWidth / 4;
                let yRadius = nodeHeight / 4;

                if (spot == human) {
                    noFill();
                    ellipse(x, y, nodeWidth / 2, nodeHeight / 2);
                } else if (spot == computer) {
                    line(x - xRadius, y - yRadius, x + xRadius, y + yRadius);
                    line(x + xRadius, y - yRadius, x - xRadius, y + yRadius)
                }
            }
        }
        if (gameInProgress && checkWinner() && currentPlayer == computer) {
            nextTurn();
        }
    }

    function mousePressed() {
        if (gameInProgress && checkWinner() && currentPlayer == human) {
            if (mouseX >= 0 && mouseY >= 0 && mouseX <= width && mouseY <= height) {
                let i = floor(mouseX / nodeWidth);
                let j = floor(mouseY / nodeHeight);
                if (moveAvailable(i, j)) {
                    board[i][j] = human;
                    currentPlayer = computer;
                }
            }
        }
    }

    function keyReleased() {
        // spacebar = key 32 ->
        if (keyCode === 32) {
            newGame();
        }
    }

    function equals3(a, b, c) {
        return a == b && b == c && a != '';
    }

    function checkWinner() {
        winner = null;
        let openSpots = 0;
        let result;
        // Horizontal Check
        for (let i = 0; i < 3; i++) {
            if (equals3(board[i][0], board[i][1], board[i][2])) {
                winner = board[i][0];
            }
        }
        // Vertical Check
        for (let j = 0; j < 3; j++) {
            if (equals3(board[0][j], board[1][j], board[2][j])) {
                winner = board[0][j];
            }
        }
        // Diagonal Checks
        if (equals3(board[0][0], board[1][1], board[2][2])) {
            winner = board[0][0];
        }
        if (equals3(board[2][0], board[1][1], board[0][2])) {
            winner = board[2][0];
        }
        for (let i = 0; i < 3; i++) {
            for (let j = 0; j < 3; j++) {
                if (board[i][j] == '') {
                    openSpots++;
                }
            }
        }

        if (winner == null && openSpots == 0) {
            result = 'tie';
        } else {
            result = winner;
        }
        if (result !== null) {
            noLoop();
            gameInProgress = false;
            currentPlayer = null;
            if (result == 'tie') {
                resultText.innerHTML = 'Tie!';
            } else {
                resultText.innerHTML = `${result} wins!`;
            }
            setScore(result);
        }
        if (result === null) {
            return true;
        } else {
            return false;
        }
    }

    function nextTurn() {
        if (currentPlayer == computer) {
            let available = [];
            for (let i = 0; i < 3; i++) {
                for (let j = 0; j < 3; j++) {
                    if (moveAvailable(i, j)) {
                        available.push({
                            i,
                            j
                        })
                    }
                }
            }
            let move = random(available);
            board[move.i][move.j] = computer;
            currentPlayer = human;
        }
    }

    function setScore(result) {
        switch (result) {
            case human:
                score[0] += 1;
                break;
            case computer:
                score[1] += 1;
                break;
            default:
                score[2] += 1;
                break;
        }
        setScoreText();
        updateScores(result);
    }

    function setScoreText() {
        scoreText.innerHTML = `${score[0]} Wins / ${score[1]} Losses / ${score[2]} Ties`;
    }

    function updateScores(result) {
        var formData = new FormData();
        switch (result) {
            case human:
                formData.append("win", 1);
                break;
            case computer:
                formData.append("loss", 1);
                break;
            default:
                formData.append("tie", 1);
                break;
        }
        formData.append("authenticity_token", "<%= form_authenticity_token %>");
        var request = new XMLHttpRequest();
        request.open("POST", "http://localhost:3000/played");
        request.send(formData);
    }

    function moveAvailable(iPos, jPos) {
        let result;
        if (iPos > 2 || jPos > 2 || iPos < 0 || jPos < 0) {
            result = false;
        } else {
            result = board[iPos][jPos] === '';
        }
        return result;
    }
</script>

app/views/pages/hiscores.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="text-center">
      All Time High Scores
    </h1>
    <% @users.each.with_index do |user, index| %>
      <p>
        Rank # <%= index + 1 %>: <%= user.username %> has won <%= pluralize(user.wins, 'Game') %> out of
        <%= pluralize(user.wins + user.losses + user.ties, 'Game') %> played.
      </p>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="jumbotron text-center">
    <h1>Tic Tac</h1>
    <p>Week 7's Project for 20 in 20 Challenge!</p>

    <% if current_user %>
      <%= link_to 'Play a Game!', game_path %>
      <br />
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Create An Account', new_user_registration_path %>
      <br />
      <%= link_to 'Login', new_user_session_path %>

    <% end %>
  </div>
</div>